from abc import ABC, abstractmethod

class Adapter(ABC):
    @abstractmethod
    def load_policy(self, model: object) -> None: ...
    @abstractmethod
    def save_policy(self, model: object) -> bool: ...
    def add_policy(self, sec: str, ptype: str, rule: list[str]) -> None: ...
    def remove_policy(self, sec: str, ptype: str, rule: list[str]) -> None: ...
    def remove_filtered_policy(
        self, sec: str, ptype: str, field_index: int, *field_values: str
    ) -> None: ...
