from casbin.persist import Adapter

class Enforcer:
    def __init__(
        self,
        model: object | None = None,
        adapter: Adapter | None = None,
        enable_log: bool = False,
    ) -> None: ...

    # Policy enforcement
    def enforce(self, *rvals: object) -> bool: ...

    # Policy management
    def add_policy(self, *params: str) -> bool: ...
    def remove_policy(self, *params: str) -> bool: ...
    def get_policy(self) -> list[list[str]]: ...
    def has_policy(self, *params: str) -> bool: ...

    # Grouping (g rules)
    def add_grouping_policy(self, *params: str) -> bool: ...
    def remove_grouping_policy(self, *params: str) -> bool: ...
    def get_grouping_policy(self) -> list[list[str]]: ...

    # RBAC domain queries
    def get_roles_for_user_in_domain(self, user: str, domain: str) -> list[str]: ...
    def get_users_for_role_in_domain(self, role: str, domain: str) -> list[str]: ...
    def get_roles_for_user(self, user: str) -> list[str]: ...
    def get_permissions_for_user(self, user: str) -> list[list[str]]: ...

    # Adapter / persistence
    def set_adapter(self, adapter: Adapter) -> None: ...
    def load_policy(self) -> None: ...
    def save_policy(self) -> None: ...

    # Model
    def new_model(self, text: str) -> object: ...
    def set_model(self, model: object) -> None: ...
    def get_model(self) -> object: ...

    # Feature flags
    def enable_auto_save(self, auto_save: bool) -> None: ...
    def enable_log(self, enable: bool) -> None: ...
    def enable_enforce(self, enable: bool) -> None: ...
